import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("window");
export { width };

export const s = StyleSheet.create({
  center: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  header: {
    backgroundColor: "#1B3A1F",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingBottom: 14,
    gap: 10,
  },
  backBtn: {
    padding: 4,
  },
  headerCenter: {
    flex: 1,
  },
  headerTitle: {
    fontFamily: "Poppins-Bold",
    fontSize: width * 0.042,
    color: "#fff",
  },
  headerSub: {
    fontFamily: "Poppins-Regular",
    fontSize: width * 0.028,
    color: "rgba(255,255,255,0.6)",
  },
  headerBadge: {
    backgroundColor: "rgba(255,255,255,0.15)",
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  headerBadgeText: {
    fontFamily: "Poppins-Bold",
    fontSize: width * 0.028,
    color: "#fff",
  },
  progressWrapper: {
    backgroundColor: "#1B3A1F",
    paddingBottom: 14,
    paddingHorizontal: 16,
  },
  progress: {
    flexDirection: "row",
    alignItems: "center",
  },
  progressStep: {
    alignItems: "center",
    gap: 4,
  },
  progressDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "rgba(255,255,255,0.3)",
    borderWidth: 1.5,
    borderColor: "rgba(255,255,255,0.4)",
  },
  progressDotActive: {
    backgroundColor: "rgba(255,255,255,0.6)",
    borderColor: "#fff",
  },
  progressDotCurrent: {
    backgroundColor: "#fff",
    width: 12,
    height: 12,
    borderRadius: 6,
  },
  progressDotInner: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#1B3A1F",
  },
  progressLine: {
    flex: 1,
    height: 1.5,
    backgroundColor: "rgba(255,255,255,0.2)",
    marginBottom: 16,
  },
  progressLineActive: {
    backgroundColor: "rgba(255,255,255,0.6)",
  },
  progressLabel: {
    fontFamily: "Poppins-Regular",
    fontSize: width * 0.025,
    color: "rgba(255,255,255,0.5)",
  },
  progressLabelActive: {
    color: "#fff",
  },
  tabsRow: {
    flexDirection: "row",
    backgroundColor: "#1B3A1F",
    paddingHorizontal: 16,
    paddingBottom: 12,
    gap: 8,
  },
  tabBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  tabBtnActive: {
    backgroundColor: "rgba(255,255,255,0.2)",
  },
  tabLabel: {
    fontFamily: "Poppins-Regular",
    fontSize: width * 0.033,
    color: "#ccc",
  },
  tabLabelActive: {
    color: "#fff",
    fontFamily: "Poppins-Bold",
  },
  techCard: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#F5F5F5",
  },
  techCardName: {
    fontFamily: "Poppins-Bold",
    fontSize: width * 0.038,
    color: "#111",
  },
  techCardRole: {
    fontFamily: "Poppins-Regular",
    fontSize: width * 0.03,
    color: "#888",
  },
  techAvatarStack: {
    flexDirection: "row",
    alignItems: "center",
  },
  techStackItem: {
    borderRadius: 23,
    borderWidth: 2,
    borderColor: "#fff",
    overflow: "hidden",
  },
  chatList: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 12,
  },
  chatEmpty: {
    alignItems: "center",
    paddingTop: 40,
  },
  chatEmptyText: {
    fontFamily: "Poppins-Regular",
    fontSize: width * 0.033,
    color: "#aaa",
    textAlign: "center",
    paddingHorizontal: 30,
  },
  msgRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 8,
  },
  msgRowRight: {
    flexDirection: "row-reverse",
  },
  bubble: {
    maxWidth: width * 0.65,
    borderRadius: 16,
    padding: 12,
  },
  bubbleTech: {
    backgroundColor: "#F5F5F5",
    borderBottomLeftRadius: 4,
  },
  bubbleCustomer: {
    backgroundColor: "#3C6034",
    borderBottomRightRadius: 4,
  },
  bubbleAuthorRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 4,
  },
  bubbleAuthor: {
    fontFamily: "Poppins-Bold",
    fontSize: width * 0.028,
    color: "#444",
  },
  supportBadge: {
    backgroundColor: "#E8F5E9",
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  supportBadgeText: {
    fontFamily: "Poppins-Bold",
    fontSize: width * 0.023,
    color: "#3C6034",
  },
  bubbleText: {
    fontFamily: "Poppins-Regular",
    fontSize: width * 0.034,
    color: "#222",
  },
  bubbleTextCustomer: {
    color: "#fff",
  },
  bubbleTime: {
    fontFamily: "Poppins-Regular",
    fontSize: width * 0.026,
    color: "#aaa",
    marginTop: 4,
    textAlign: "right",
  },
  bubbleTimeCustomer: {
    color: "rgba(255,255,255,0.6)",
  },
  sysMsg: {
    alignSelf: "center",
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 8,
    marginVertical: 6,
    maxWidth: width * 0.78,
    gap: 4,
  },
  sysMsgHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  sysMsgLabel: {
    fontFamily: "Poppins-Bold",
    fontSize: width * 0.028,
  },
  sysMsgText: {
    fontFamily: "Poppins-Regular",
    fontSize: width * 0.031,
    lineHeight: 18,
    color: "#92400E",
  },
  inputRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: "#F0F0F0",
    backgroundColor: "#fff",
  },
  attachBtn: {
    padding: 6,
  },
  chatInput: {
    flex: 1,
    backgroundColor: "#F5F5F5",
    borderRadius: 22,
    paddingHorizontal: 16,
    paddingVertical: 10,
    fontFamily: "Poppins-Regular",
    fontSize: width * 0.034,
    maxHeight: 100,
    color: "#222",
  },
  sendBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#3C6034",
    justifyContent: "center",
    alignItems: "center",
  },
  sendBtnDisabled: {
    backgroundColor: "#B0C4B1",
  },
  attachImg: {
    width: width * 0.5,
    height: width * 0.4,
    borderRadius: 10,
    marginTop: 6,
  },
  pendingRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: "#F0F0F0",
    backgroundColor: "#fff",
  },
  pendingThumb: {
    position: "relative",
  },
  pendingImg: {
    width: 56,
    height: 56,
    borderRadius: 8,
  },
  pendingRemove: {
    position: "absolute",
    top: -6,
    right: -6,
    backgroundColor: "#fff",
    borderRadius: 10,
  },
  infoScroll: {
    padding: 16,
    gap: 14,
  },
  infoCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "#F0F0F0",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 2,
  },
  infoCardTitle: {
    fontFamily: "Poppins-Bold",
    fontSize: width * 0.04,
    color: "#111",
    marginBottom: 14,
  },
  stepsRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  stepItem: {
    alignItems: "center",
    gap: 6,
    width: 70,
  },
  stepCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#F0F0F0",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#E0E0E0",
  },
  stepCircleActive: {
    backgroundColor: "#3C6034",
    borderColor: "#3C6034",
  },
  stepNum: {
    fontFamily: "Poppins-Bold",
    fontSize: 15,
    color: "#aaa",
  },
  stepNumActive: {
    color: "#fff",
  },
  stepLabel: {
    fontFamily: "Poppins-Regular",
    fontSize: width * 0.028,
    color: "#aaa",
    textAlign: "center",
  },
  stepLabelActive: {
    color: "#3C6034",
    fontFamily: "Poppins-Bold",
  },
  stepLine: {
    flex: 1,
    height: 2,
    backgroundColor: "#E8E8E8",
    marginBottom: 20,
  },
  stepLineActive: {
    backgroundColor: "#3C6034",
  },
  detailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#F5F5F5",
  },
  detailLabel: {
    fontFamily: "Poppins-Regular",
    fontSize: width * 0.033,
    color: "#888",
  },
  detailValue: {
    fontFamily: "Poppins-Regular",
    fontSize: width * 0.033,
    color: "#111",
    textAlign: "right",
    flex: 1,
    paddingLeft: 20,
  },
  warrantyBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
  },
  warrantyActive: {
    backgroundColor: "#F0FDF4",
  },
  warrantyExpired: {
    backgroundColor: "#FEF2F2",
  },
  warrantyDot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
  },
  warrantyText: {
    fontFamily: "Poppins-Bold",
    fontSize: width * 0.03,
  },
  infoDesc: {
    fontFamily: "Poppins-Regular",
    fontSize: width * 0.034,
    color: "#444",
    lineHeight: 22,
  },
  techRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 6,
  },
  techName: {
    fontFamily: "Poppins-Bold",
    fontSize: width * 0.036,
    color: "#111",
  },
  techRole: {
    fontFamily: "Poppins-Regular",
    fontSize: width * 0.03,
    color: "#888",
  },
  cancelBtn: {
    backgroundColor: "#FEF2F2",
    borderRadius: 16,
    paddingVertical: 16,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#FECACA",
  },
  cancelBtnText: {
    fontFamily: "Poppins-Bold",
    fontSize: 15,
    color: "#DC2626",
  },
  pausedBanner: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderTopWidth: 1,
  },
  pausedBannerText: {
    flex: 1,
    fontFamily: "Poppins-Regular",
    fontSize: width * 0.031,
    lineHeight: 18,
  },
  cancelJustifyHint: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: 1,
  },
  cancelJustifyText: {
    flex: 1,
    fontFamily: "Poppins-Regular",
    fontSize: width * 0.031,
    lineHeight: 18,
  },
  chatClosedBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 16,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: "#F0F0F0",
    backgroundColor: "#FAFAFA",
  },
  chatClosedText: {
    flex: 1,
    fontFamily: "Poppins-Regular",
    fontSize: width * 0.031,
    color: "#6B7280",
  },
  closedInfoBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    borderRadius: 16,
    padding: 18,
    borderWidth: 1,
  },
  closedInfoBannerGreen: {
    backgroundColor: "#F0FDF4",
    borderColor: "#BBF7D0",
  },
  closedInfoBannerRed: {
    backgroundColor: "#FEF2F2",
    borderColor: "#FECACA",
  },
  closedInfoTitle: {
    fontFamily: "Poppins-Bold",
    fontSize: width * 0.038,
    marginBottom: 2,
  },
  closedInfoSub: {
    fontFamily: "Poppins-Regular",
    fontSize: width * 0.03,
    color: "#6B7280",
    lineHeight: 18,
  },

  imgModalBg: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.95)",
    justifyContent: "center",
  },
  imgModalClose: {
    position: "absolute",
    top: 50,
    right: 18,
    zIndex: 10,
    backgroundColor: "rgba(255,255,255,0.15)",
    borderRadius: 20,
    padding: 6,
  },
  imgModalScroll: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  imgModalImg: {
    width,
    height: width * 1.2,
  },

  offHoursBanner: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderTopWidth: 1,
  },
  offHoursText: {
    flex: 1,
    fontFamily: "Poppins-Regular",
    fontSize: width * 0.029,
    lineHeight: 17,
  },
  errorTitle: {
    fontFamily: "Poppins-Bold",
    fontSize: width * 0.042,
    color: "#374151",
    marginTop: 16,
    textAlign: "center",
  },
  errorSub: {
    fontFamily: "Poppins-Regular",
    fontSize: width * 0.033,
    color: "#9CA3AF",
    textAlign: "center",
    marginTop: 6,
    paddingHorizontal: 32,
  },
  retryBtn: {
    marginTop: 20,
    backgroundColor: "#3C6034",
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 32,
  },
  retryBtnText: {
    fontFamily: "Poppins-Bold",
    fontSize: width * 0.037,
    color: "#FFF",
  },
});
